version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name : build-mongodb-backup-34
          command: |
            docker build . -t quay.io/wealthwizards/mongodb-backup:3.4 --build-arg MONGO_MAJOR=34
      - run:
          name : build-mongodb-backup-36
          command: |
            docker build . -t quay.io/wealthwizards/mongodb-backup:3.6 --build-arg MONGO_MAJOR=36
            docker tag quay.io/wealthwizards/mongodb-backup:3.6 quay.io/wealthwizards/mongodb-backup:latest
  buildAndDeploy:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name : build-mongodb-backup-34
          command: |
            docker build . -t quay.io/wealthwizards/mongodb-backup:3.4 --build-arg MONGO_MAJOR=34
      - run:
          name : build-mongodb-backup-36
          command: |
            docker build . -t quay.io/wealthwizards/mongodb-backup:3.6 --build-arg MONGO_MAJOR=36
            docker tag quay.io/wealthwizards/mongodb-backup:3.6 quay.io/wealthwizards/mongodb-backup:latest
      - deploy:
          name : docker-login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
      - deploy:
          name : push-mongodb-backup-34
          command: |
            docker push quay.io/wealthwizards/mongodb-backup:3.4
      - deploy:
          name : push-mongodb-backup-36
          command: |
            docker push quay.io/wealthwizards/mongodb-backup:3.6
            docker push quay.io/wealthwizards/mongodb-backup:latest
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              ignore: master
